#!/bin/sh
# Regenerates Sources/Periscope/Generated/EmbeddedSkill.swift from skill/, so
# `periscope install-skill` works from a lone binary. Run after editing skill/;
# EmbeddedSkillTests fails when the two drift.
set -eu
cd "$(dirname "$0")/.."
out=Sources/Periscope/Generated/EmbeddedSkill.swift
{
    echo "// Generated by scripts/embed-skill.sh from skill/. Do not edit."
    echo "enum EmbeddedSkill {"
    echo "    /// Path inside the skill folder, contents, and whether it is executable."
    echo "    static let files: [(path: String, contents: String, executable: Bool)] = ["
    find skill -type f ! -name '.DS_Store' | sort | while read -r f; do
        rel=${f#skill/}
        exe=false; [ -x "$f" ] && exe=true
        printf '        ("%s", ##"""\n' "$rel"
        cat "$f"
        printf '"""##, %s),\n' "$exe"
    done
    echo "    ]"
    echo "}"
} > "$out"
echo "wrote $out"
