#!/bin/sh
# Regenerates Sources/Periscope/Generated/EmbeddedSkill.swift from
# skills/periscope/ and PERISCOPE.md, so `periscope install-skill` and
# `periscope docs` work from a lone binary. Run after editing either;
# EmbeddedSkillTests fails when they drift.
set -eu
cd "$(dirname "$0")/.."
out=Sources/Periscope/Generated/EmbeddedSkill.swift
dir=skills/periscope
{
    echo "// swift-format-ignore-file"
    echo "// Generated by scripts/embed-skill.sh from $dir/ and PERISCOPE.md. Do not edit."
    echo "enum EmbeddedSkill {"
    echo "    /// Path inside the skill folder, contents, and whether it is executable."
    echo "    static let files: [(path: String, contents: String, executable: Bool)] = ["
    find "$dir" -type f ! -name '.DS_Store' | sort | while read -r f; do
        rel=${f#"$dir"/}
        exe=false; [ -x "$f" ] && exe=true
        printf '        ("%s", ##"""\n' "$rel"
        cat "$f"
        printf '"""##, %s),\n' "$exe"
    done
    echo "    ]"
    echo ""
    echo "    /// PERISCOPE.md, the full command reference (\`periscope docs\`)."
    printf '    static let reference = ##"""\n'
    cat PERISCOPE.md
    printf '"""##\n'
    echo "}"
} > "$out"
echo "wrote $out"
